FROM nginx

COPY nginx/default.conf.ssl /etc/nginx/conf.d/default.conf
COPY nginx/locations /etc/nginx/conf.d/
COPY nginx/upstreams /etc/nginx/conf.d/

COPY ./tls/MPCServer/MPCServer.pem /etc/nginx/conf.d/
COPY ./tls/rootCA/rootCA.crt /etc/nginx/conf.d/
